const String appName = "ThirstQuest";
const double markerSize = 45.0;
const double markerPadding = 5.0;
const double nearestBubblersLatLonDelta = 0.025;
const double bigInfoCardHeight = 0.7;
const double smallInfoCardHeight = 1 / 7;
const int shortAnimationDuration = 250;
const int longAnimationDuration = 500;
const int minCharsForSearch = 2;
